# Generated by Django 4.0.2 on 2022-08-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KKWIEER_Hostel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
