# Generated by Django 4.0.2 on 2022-08-16 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KKWIEER_Hostel', '0002_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('Hostel Problem', 'Hostel Problem'), ('Mess Problem', 'Mess Problem'), ('Ragging Case', 'Ragging Case'), ('Fees Issue', 'Fees Issue')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Viewed', 'Viewed'), ('Completed', 'Completed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KKWIEER_Hostel.student'),
        ),
    ]
