# Generated by Django 4.0.2 on 2022-08-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KKWIEER_Hostel', '0003_complaint_category_complaint_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
