# Generated by Django 4.0.2 on 2022-08-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KKWIEER_Hostel', '0004_complaint_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fees_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], max_length=200, null=True),
        ),
    ]
